### ISSUE TITLE
Problemas en formulario offline con campo customer_name

### ISSUE THREAD

**Issue by mafecito** [decidir/sdk-javascript-v2#2]
Que tal, estoy teniendo problemas con el formulario offline, el SDK me está dando error en el campo customer_name

```
"Cannot read property 'name' of undefined"
stack
:
"TypeError:
 Cannot read property 'name' of undefined↵ at t.value (https://live.decidir.com/static/v1/decidir.js:2:9094)↵ at t.value (https://live.decidir.com/static/v1/decidir.js:2:8096)↵ at t.value (https://live.decidir.com/static/v1/decidir.js:1:19159)↵ at Store.createToken
 (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:22100:15)↵ at Array.wrappedActionHandler (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:21261:23)↵ at Store.dispatch (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:20983:15)↵ at Store.boundDispatch
 [as dispatch] (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:20889:21)↵ at VueComponent.mappedAction (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:21437:20)↵ at VueComponent.boundFn [as createToken] (https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:10168:14)↵
 at https://pagos.dev/dist/app.js?id=56a3612d8d29873103da:2118:19"
```

Mas precisamente aquí:
```

key: "validateRequestWithOfflineData",
        value: function(t) {
            var e = [];
            e.push(**this.cardHolderNameValidator(t.customer.name)**);
            var a = e.every(function(t) {
                return t.isValid
            })
              , r = e.filter(function(t) {
                return !t.isValid
            });
            return {
                isValid: a,
                errors: r
            }
        }
```

```
function(t) {
            for (var e = t.querySelectorAll("[data-decidir]"), a = {}, r = {}, i = {}, n = {}, o = 0; e.length > o; o++) {
                var s = e[o]
                  , l = s.getAttribute("data-decidir");
                l.lastIndexOf("card_holder_doc_") !== -1 || l.lastIndexOf("customer_") !== -1 ? (l.lastIndexOf("card_holder_doc_") !== -1 && (r[l.replace("card_holder_doc_", "")] = s.value),
                l.lastIndexOf("customer_doc_") !== -1 && (i[l.replace("customer_doc_", "")] = s.value),
                l.lastIndexOf("customer_name") !== -1 && (n[l.replace("customer_name", "name")] = s.value)) : a[l] = s.value
            }
            var d = a.card_holder_door_number;
            d && d.trim() || delete a.card_holder_door_number;
            var c = a.card_holder_birthday;
            **return c && c.trim() || delete a.card_holder_birthday,
            n.identification = i,
            0 !== Object.keys(r).length && r.constructor === Object ? a.card_holder_identification = r : a.customer = n,
            a**
```
Saludos y muchas gracias

**Comment by ignaciovalek** [comment]
Hola. Revisamos este caso y encontramos que había un error en la documentación. 
En el caso de un **Pago Offline**, en el campo _"Tipo de documento"_ el atributo `data-decidir` deber ser "_customer_doc_type_", cuando en el **README** decía "_card_holder_doc_type_".

Saludos

**Ejemplo**
```
<label for="customer_doc_type">Tipo de documento:</label>
<select data-decidir="customer_doc_type">
    <option value="dni">DNI</option>
</select>
```

**Comment by mafecito** [comment]
Que tal, hice el cambio, y con la version 1 del SDK puedo crear el token ahora, pero también actualizaron en la documentación la versión del SDK de la v1 a la 1.1, y con esa versión no me funciona esto tampoco. No crea el token porque me dice que faltan campos que no corresponden al pago offline.

Adjunto session del debuger donde da error.

Saludos y muchas gracias

![error-pago-offline](https://user-images.githubusercontent.com/6381409/32788622-7ba30ca8-c938-11e7-8d85-edc728f707b6.jpg)

**Comment by ignaciovalek** [comment]
Hola, por el momento utilizá la v1. Tuvimos problemas y se pisaron mal las versiones.

Gracias por el aviso.

Saludos!
